### ISSUE TITLE
Compressing Images in a GridView leads to app crash

### ISSUE THREAD

**Issue by k2evil** [OpenFlutter/flutter_image_compress#94]
Hi... I show a list of the Images stored in the external storage. Since it was too laggy specially when it came to large images, I decided to use your library to compress the image before it been shown in the list.
But the problem is after showing about 200-250 items, Application crashes without any logs... I monitored the memory usage of the application and I guess it's because of `OutOfMemoryException`.
Is there anyway to remove older images from memory to avoid this problem?
```
class GalleryGridView extends StatelessWidget {
  final List<FileSystemEntity> data;

  GalleryGridView({@required this.data});

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 3,
            childAspectRatio: 1 / 1,
            crossAxisSpacing: 2.0,
            mainAxisSpacing: 2.0),
        itemCount: data?.length ?? 0,
        itemBuilder: (context, index) {
          return FutureBuilder<List<int>>(
              future: FlutterImageCompress.compressWithFile(
              data[index].path,
              minHeight: (MediaQuery.of(context).size.width / 3).floor(),
              minWidth: (MediaQuery.of(context).size.width / 3).floor(),
              quality: 80,
            ),
            builder: (context, snapshot) {
              print('$index : ${data[index]}');
              return Container(
                decoration: BoxDecoration(color: Colors.grey[300]),
                child: snapshot.data != null && snapshot.error == null
                    ? FadeInImage(
                        placeholder: MemoryImage(kTransparentImage),
                        image: MemoryImage(Uint8List.fromList(snapshot.data)),
                        fit: BoxFit.cover,
                      )
                    : null,
              );
            },
          );
        });
  }
}
```

**Comment by k2evil** [comment]
```
E/AndroidRuntime(32303): java.lang.OutOfMemoryError: Failed to allocate a 366530280 byte allocation with 6291456 free bytes and 254MB until OOM, max allowed footprint 7868488, growth limit 268435456
E/AndroidRuntime(32303): 	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:68)
E/AndroidRuntime(32303): 	at com.example.flutterimagecompress.core.CompressFileHandler$handle$1.run(CompressFileHandler.kt:36)
E/AndroidRuntime(32303): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(32303): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(32303): 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by k2evil** [comment]
Ok... I found the problem... I was passing a large video file to image compressor
